# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: gitpod-dev-env
    init: |
      pip install --upgrade pip
      pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin mkdocs-awesome-pages-plugin mkdocs-git-revision-date-plugin

vscode:
  extensions:
    - ms-python.python
