name: 'Mirror a repository using SSH'
description: 'Action for mirroring a repository in another location (Bitbucket, GitHub, GitLab, …) using SSH.'
branding:
  icon: 'copy'
  color: 'orange'
inputs:
  source-repo:
    description: 'SSH URL of the source repo.'
    required: true
    default: 'git@github.com:LeeSamoyed/leesamoyed.github.io.git'
  destination-repo:
    description: 'SSH URL of the destination repo.'
    required: true
    default: 'git@gitee.com:leesamoyed/leesamoyed.gitee.io.git'
  dry-run:
    description: 'Execute a dry run.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-repo }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.dry-run }}