site_name: Yam Lee Wiki
site_url: https://leesamoyed.github.io/
site_author: Yi Li
site_description: >-
  Blog

repo_name: 'LeeSamoyed/leesamoyed.github.io'
repo_url: 'https://github.com/LeeSamoyed/leesamoyed.github.io'
edit_uri: 'edit/master/.docs/'

# Docs
docs_dir: '.docs'

# Configuration
theme:
  name: material
  # custom_dir: .docs/.overrides
  features:
    - navigation.instant
    # - navigation.tracking
    # - announce.dismiss
    - content.action.edit
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand # 开启 sidebar 侧栏默认展开
    ## - navigation.path # 开启路径
    ## - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # 不开 sidebar 侧栏可以为点击收缩
    ## - navigation.tabs
    # - navigation.tabs.sticky
    ## - navigation.top
    ## - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    


# Plugins
plugins:
  - search
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  #       conventions.md: philosophy.md
  #       reference/abbreviations.md: reference/tooltips.md
  #       reference/meta-tags.md: reference/index.md
  #       reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
  #       sponsorship.md: insiders/index.md
  #       upgrading.md: upgrade.md
  - minify:
      minify_html: true
  - git-revision-date

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - meta
  - footnotes
  - md_in_html
  - codehilite:
      guess_lang: false
      linenums: false
  - toc: # Subsection
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.arithmatex: # Mathematical Formula
      generic: true

# extra_javascript
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:leesamoyed@163.com
    - icon: fontawesome/brands/github
      link: https://github.com/LeeSamoyed/

# Page tree
nav:
  - 主页: index.html
  - 关于我: 
    - 简历: aboutme/resume.md
    - 项目: aboutme/project.md
    - 学术: aboutme/academic.md
  - 编程&算法:
    - 编程语言:
      - Go语言标准库:  programming-algorithm/programming-language/go-standard-library.md
      - Go in Action: programming-algorithm/programming-language/go-in-action.md
      - Go转型: programming-algorithm/programming-language/go-transformation.md
      - Python Crash Course: programming-algorithm/programming-language/python-crash-course.md
      - Python基础扩展 优课达: programming-algorithm/programming-language/python-extension-ykd.md
      - C++ Primer: programming-algorithm/programming-language/c-primer.md
      - 环境搭建: programming-algorithm/programming-language/environment-build.md
    - 程序算法:
      - LeetCode: programming-algorithm/algorithm/leetcode.md
      - 基本数据结构: programming-algorithm/algorithm/data-structure-basic.md
  - 研发&设计:
    - 研发:
      - 数据库系统:
        - MySQL是怎样运行的: research-development-design/sql/how-mysql-work-understand-from-root.md
        - MySQL必知必会: research-development-design/sql/sams-teach-yourself-sql-in-10-minutes.md
      - 开发框架:
        - 框架综述: research-development-design/development-framework/summarize.md
      - 流量:
        - Nginx: research-development-design/flow/nginx.md
      - 测试:
        - Testcase设计: research-development-design/test/testcase-design.md
    - 设计:
      - 系统设计:
        - 解耦: research-development-design/system-design/decoupling.md
        - 扩展性: research-development-design/system-design/extensibility.md
        - 模块化设计: research-development-design/system-design/modular-design.md
        - 健壮性: research-development-design/system-design/robustness.md
        - 简化操作: research-development-design/system-design/simplified-operation.md
      - 需求分析与设计:
        - 分析与设计: research-development-design/requirements-analysis-design/analysis-design.md
      - 业务逻辑:
        - 请求的安全与健全: research-development-design/business-logic/soundness-and-security-of-requests.md
        - 唯一数据插入: research-development-design/business-logic/unique-insert.md
        - 标识位的利用: research-development-design/business-logic/flag-is-important.md
        - 算法的引入: research-development-design/business-logic/algorithm.md
      - 设计模式:
        - 大话设计模式: research-development-design/design-pattern/westward-design-patterns.md
  - 嵌入式:
    - 开发板:
      - Jetson + 视觉: embedded/development-board/jetson-vision.md
  - 云原生:
    - 体系:
      - 云原生综述: cloud-native/system/summarize.md
      - VPC: cloud-native/system/vpc.md
      - Docker: cloud-native/system/docker.md
      - Kubernetes: cloud-native/system/k8s.md
      - DevOps: cloud-native/system/devops.md
      - Micro Services: cloud-native/system/micro-services.md
      - Service Mesh: cloud-native/system/service-mesh.md
    - 工具:
      - KuberShpere: cloud-native/platform/kubersphere.md
      - Jenkins: cloud-native/platform/jenkins.md
    - 搭建&维护:
      - AKS SelfHost Gitpod: cloud-native/build-ops/aks-selfhost-gitpod.md
      - AKS QDUOJ: cloud-native/build-ops/aks-qduoj.md
  - 网络安全:
    - 渗透测试:
      - 信息收集: cyber-security/penetration-test/information-gathering.md
      - OWASP-Top10: cyber-security/penetration-test/owasp-top10.md
      - CMS: cyber-security/penetration-test/cms.md
      - 靶场相关: cyber-security/penetration-test/range-relevant.md
    - 代码审计:
      - 审计流程: cyber-security/code-audit/audit-process.md
      - 危险函数关键字: cyber-security/code-audit/dangerous-function-keyword.md
    - 爬虫:
      - 爬虫综述: cyber-security/crawler/summarize.md
    - 工具:
      - 抢占式服务器配置: cyber-security/tools/preemptive-server-configuration.md
      - ECS代理池: cyber-security/tools/ecs-proxypool.md
      - 工具相关: cyber-security/tools/tool-relevant.md
  - 机器&深度学习:
    - 机器学习:
      - 频率派&贝叶斯派: machine-deep-learning/machine-learning/frequentist&bayesian.md
      - 高斯分布: machine-deep-learning/machine-learning/gaussian-distribution.md
      - 回归: machine-deep-learning/machine-learning/regression.md
      - 线性分类: machine-deep-learning/machine-learning/linear-classification.md
    - 深度学习:
      - 基本概念: machine-deep-learning/deep-learning/concept.md
      - 神经网络架构搜索: machine-deep-learning/deep-learning/neural-architecture-search.md
      - 注意力机制: machine-deep-learning/deep-learning/attention-mechanism.md
      - 计算机视觉: machine-deep-learning/deep-learning/computer-vision.md
      - 自然语言处理: machine-deep-learning/deep-learning/natural-language-processing.md
      - 时序预测: machine-deep-learning/deep-learning/time-series-prediction.md
      - 深度学习框架: machine-deep-learning/deep-learning/open-source-library.md
    - 统计学习方法: 
      - 感知机: machine-deep-learning/statistical-methods/perceptron.md
      - K近邻: machine-deep-learning/statistical-methods/k-nearest-neighbor.md
    - 深度学习之PyTorch物体检测实战:
      - 浅谈物体检测和PyTorch: machine-deep-learning/deep-learning-pytorch-object-detection/pytorch-object-detection.md
      - Pytorch基础: machine-deep-learning/deep-learning-pytorch-object-detection/pytorch-basic.md
    - 论文整理: machine-deep-learning/paper-arrangement.md
    - 数据集整理: machine-deep-learning/databases.md
  - 分布式系统:
    - 分布式一致性算法: distributed-systems/distributed-consistency-algorithm.md
  - 代码改进:
    - QDUOJ 青岛大学开源OJ系统: code-improvements/qduoj.md
  - 数理:
    - 微积分:
      - 微积分的本质: mathematical-theory/calculus/nature-of-calculus.md
      - 导数的悖论: mathematical-theory/calculus/paradox-of-derivatives.md
      - 用几何求导: mathematical-theory/calculus/geometric-derivation.md
      - 直观理解链式法则和乘法法则: mathematical-theory/calculus/chain-rule-multiplication-rule.md
      - 指数函数求导: mathematical-theory/calculus/exponential-function-derivation.md
      - 隐函数求导: mathematical-theory/calculus/implicit-function-derivation.md
      - 极限: mathematical-theory/calculus/limit.md
      - 积分与微积分基本定理: mathematical-theory/calculus/integration-and-calculus.md
      - 面积和斜率的关系: mathematical-theory/calculus/area-and-slope.md
      - 高阶导数: mathematical-theory/calculus/higher-order-derivative.md
      - 泰勒级数: mathematical-theory/calculus/taylor-series.md
    - 扩展:
      - 虚数和实数: mathematical-theory/expand/imaginary-and-real-numbers.md
      - 最美的公式: mathematical-theory/expand/euler-formula.md
      - exp&e: mathematical-theory/expand/exp-e.md
  - 资源&心得:
    - 学习路线:
      - 纯开发: resources-opinion/study-routes/develop-research.md
      - 设计模式: resources-opinion/study-routes/design-pattern.md
      - 云原生: resources-opinion/study-routes/cloud-native.md
      - 网络安全: resources-opinion/study-routes/cyber-security.md
      - 大数据: resources-opinion/study-routes/big-data.md
      - 机器学习: resources-opinion/study-routes/machine-learning.md
      - 深度学习: resources-opinion/study-routes/deep-learning.md
      - 爬虫: resources-opinion/study-routes/crawler.md
      - 嵌入式开发: resources-opinion/study-routes/embedded-development.md
      - 数学理论: resources-opinion/study-routes/mathematical-theory.md
      - 论文写作: resources-opinion/study-routes/paper.md
    - 复习:
      - 开发: resources-opinion/review/research-and-development.md
    - 使用手册:
      - Git: resources-opinion/manuals/git.md
      - Docker: resources-opinion/manuals/docker.md
      - Latex: resources-opinion/manuals/latex.md
    - 效率提升:
      - MacOS自我修养: resources-opinion/efficiency-improvement/macos.md
      - 通用自我修养: resources-opinion/efficiency-improvement/common.md
    - 操作系统相关问题: 
      - LinuxOS: resources-opinion/operation-system-issue/linuxos.md
      - WindowsOS: resources-opinion/operation-system-issue/windowsos.md
  - 知识:
    - 知识清单: knowledge/knowledge-list.md
    - 新概念:
      - 元宇宙: knowledge/new-concept/metaverse.md