name: Repo 2 Gitee

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Repo 2 Gitee
      uses: LeeSamoyed/LeeSamoyed.git.io@v1.1
      with:
        src: github/LeeSamoyed
        dst: gitee/LeeSamoyed
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: user
        clone_style: "https"
        debug: true 
        force_update: true 
        static_list: "python-nianbao-struct"
        timeout: '600s'
