name: Repo2Gitee
on:
  push:
    branches:
      - master
jobs:
  repo2gitee:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Repo to Gitee
        uses: LeeSamoyed/leesamoyed.github.io@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:LeeSamoyed/leesamoyed.github.io.git"
          destination-repo: "git@gitee.com:leesamoyed/leesamoyed.gitee.io.git"

      # - name: Build Gitee Pages
      #   uses: leesamoyed/leesamoyed.gitee.io@master
      #   with:
      #     gitee-username: LeeSamoyed
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     gitee-repo: leesamoyed/leesamoyed.gitee.io
      #     branch: master
