name: repo2gitee
on:
  push:
    branches:
      - master
jobs:
  repo2gitee:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: repo2gitee
        uses: LeeSamoyed/leesamoyed.github.io@master
